apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017 # porta para o service 
      targetPort: 27017 # porta para o container Pod
  type: ClusterIP